### ISSUE TITLE
Conserver le dernier chargement réussi d'une session à la suivante

### ISSUE THREAD

**Issue by avianey** [Ryovenly/Meteo-Mobile#1]
Quand on rouvre l'application,
Charger de nouveau la météo pour la dernière ville chargée

**Comment by Ryovenly** [comment]
![2021-03-03_22h23_19](https://user-images.githubusercontent.com/43552846/109874190-132f1980-7c6f-11eb-9c89-ef4f04f756d0.png)
Fonctionne avec le debug et les points d'arrets quand je met dans la ligne 271 et 273 mais pas normalement, il y a une erreur NullPointer si je lance sans le debug.

![2021-03-03_22h27_28](https://user-images.githubusercontent.com/43552846/109874619-a5372200-7c6f-11eb-9508-5fc085fbdace.png)

**Comment by Ryovenly** [comment]
![2021-03-03_22h31_58](https://user-images.githubusercontent.com/43552846/109875085-44f4b000-7c70-11eb-89cf-ba13f72ca6a8.png)

Résolu en laissant un peu de temps pour la variable resultat de se charger avec la fontion Handler et en laissant un délai.
