### ISSUE TITLE
Implémenter le style Material

### ISSUE THREAD

**Issue by avianey** [Ryovenly/Meteo-Mobile#3]
https://material.io/develop/android/docs/getting-started

Afficher la météo courrante via une MaterialCardView : https://material.io/components/cards

**Comment by coolofdead** [comment]
![image](https://user-images.githubusercontent.com/45070722/109946350-6ee1bd00-7cd8-11eb-8dbf-47d01b0fd193.png)
Implem du card material design cependant, il semble y a voir un problème avec la taille par défaut du champ Title (plus petit que ce qu'il devrait être)
